apiVersion: apps/v1
kind: Deployment
metadata:
  name: efv-icbc-api
  labels:
    app: efv-icbc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efv-icbc-api
  template:
    metadata:
      labels:
        app: efv-icbc-api
    spec:
      containers:
        - name: efv-icbc-api
          image: REPLACE_WITH_IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
